In [2]:
import tensorflow as tf 
tf.enable_eager_execution()

In [3]:
import numpy as np
a = np.array([[1,1,1],[2,2,2],[3,3,3]],dtype=np.float32)

In [4]:
b=tf.reshape(a,[a.shape[0],1,a.shape[1],1])

In [5]:
k=tf.constant([[[[ 1.0, 1.0]],[[2.0,  2.0]]]], dtype=tf.float32)

In [6]:
mycov=tf.nn.conv2d(b, k, [1, 1, 1, 1], padding='SAME')

In [7]:
print(mycov)

tf.Tensor(
[[[[3. 3.]
   [3. 3.]
   [1. 1.]]]


 [[[6. 6.]
   [6. 6.]
   [2. 2.]]]


 [[[9. 9.]
   [9. 9.]
   [3. 3.]]]], shape=(3, 1, 3, 2), dtype=float32)


In [9]:
print(mycov.shape)

(3, 1, 3, 2)


In [11]:
c = tf.constant([1,2,3])

In [12]:
tf.squeeze(c)

<tf.Tensor: id=8, shape=(3,), dtype=int32, numpy=array([1, 2, 3], dtype=int32)>

In [13]:
print(c.shape)

(3,)


In [15]:
c = tf.constant([[1],[2],[3]])

In [16]:
print(c.shape)

(3, 1)


In [17]:
tf.squeeze(c)

<tf.Tensor: id=11, shape=(3,), dtype=int32, numpy=array([1, 2, 3], dtype=int32)>

In [18]:
print(c)

tf.Tensor(
[[1]
 [2]
 [3]], shape=(3, 1), dtype=int32)


In [19]:
tf.squeeze(c).shape

TensorShape([Dimension(3)])

In [20]:
c.shape

TensorShape([Dimension(3), Dimension(1)])

In [26]:
c = tf.constant([1,2,3],dtype=float)

In [27]:
tf.sigmoid(c)

<tf.Tensor: id=17, shape=(3,), dtype=float32, numpy=array([0.7310586 , 0.880797  , 0.95257413], dtype=float32)>

In [37]:

input = [[[1, 1, 1], [2, 2, 2]],
         [[3, 4, 5], [4, 4, 4]],
         [[5, 5, 5], [6, 6, 6]]]

In [39]:
tf.slice(input, [1, 0, 0], [1, 2, 3])

<tf.Tensor: id=45, shape=(1, 2, 3), dtype=int32, numpy=
array([[[3, 4, 5],
        [4, 4, 4]]], dtype=int32)>

In [30]:
tf.slice(input, [1, 0,0], [1, 1m])

InvalidArgumentError: Expected begin and size arguments to be 1-D tensors of size 3, but got shapes [2] and [2] instead. [Op:Slice]

In [31]:
print(input[0])

[[1, 1, 1], [2, 2, 2]]


In [32]:
print(input[1])

[[3, 3, 3], [4, 4, 4]]


In [34]:
print(input[1][0][0])

3


In [ ]:
print(input[1][0][0])